In [1]:
import torch
from transformer_for_ts import Transformer

# Model parameters
d_model = 113
q = 2
v = 2
h = 2
N = 4
d_ff = 64
dropout = 0

d_input = 113
d_output = 9

In [2]:
net = Transformer(d_input, d_model, d_output, q, v, h, N, d_ff, dropout=dropout, compute_value=1).cuda()

In [3]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

In [4]:
print(f'The model has {count_parameters(net.layers_encoding):,} trainable parameters')

The model has 68,104 trainable parameters


In [5]:
print(f'The model has {count_parameters(net.layers_decoding):,} trainable parameters')

The model has 76,740 trainable parameters


In [6]:
print(f'The model has {count_parameters(net):,} trainable parameters')

The model has 158,752 trainable parameters


In [7]:
input = torch.ones(1,6,113).cuda()

In [8]:
word_length = torch.tensor([4])

In [9]:
a1 = net(input, word_length)

In [15]:
input1 = torch.cat((torch.ones(1,12,113), torch.zeros(1,3,113)), dim = 1).cuda()

In [16]:
a2 = net(input1, word_length)

In [17]:
a1

tensor([[-3.3898,  2.2644, -6.6018,  4.4159, -1.9846,  0.9979,  1.1323,  4.5594,
         -2.2332]], device='cuda:0', grad_fn=<SumBackward1>)

In [18]:
a2

tensor([[ -8.5672,   5.7247, -16.9842,  10.7948,  -4.7113,   3.0621,   3.4407,
          11.5518,  -5.2687]], device='cuda:0', grad_fn=<SumBackward1>)

In [14]:
a2*5/6

tensor([[-2.8359,  1.8968, -5.5388,  3.6663, -1.6219,  0.8749,  0.9992,  3.7962,
         -1.8224]], device='cuda:0', grad_fn=<DivBackward0>)